print('Soma e multiplicação entre dois números')
num1=float(input('Digite um número: '))
num2=float(input('Digite mais um número: '))
soma=float(num1+num2)
multi=float(num1*num2)
print('O resultado da soma entre os dois números será: %.2f' % soma)
print('O resultado da multiplicação entre os dois números será:%.2f' % multi)